### ISSUE TITLE
inference on custom dataset

### ISSUE THREAD

**Issue by ooza** [Yuchen413/AnomalyRuler#1]
Hello, thanks for this great work!
I'm working on video surveillance domain using VLMs and LLMs, and found your work interesting! Yet, the readme should be more clearer regarding the use of a custom data:
should I prepare the csv files as you did for Ped2 and the other datasets?
I've a small dataset of 280 short video clips.
what files should I prepare before running your scripts ?
Thanks

**Comment by Yuchen413** [comment]
Hello, thanks for your questions. 
You can refer to: 

https://github.com/Yuchen413/AnomalyRuler/blob/7eb88426acb6e808206abdcba11e4fc356b47ba6/dataset.py#L61

This is for extracting frames from video clips and saving them as frames. You may need to organize your video into folders like ['data/test/normal', 'data/test/abnormal', 'data/train'] (see comments under the function), or slightly modify the code to fit your folder name.

**Comment by witty1011** [comment]
hi, ooza. I'm trying doing same thing as you're. Just wondering if u already suceed?
