### ISSUE TITLE
How use GPT for deduct?

### ISSUE THREAD

**Issue by angel-ayala** [Yuchen413/AnomalyRuler#4]
Hi, 

I saw in your paper that also used the GPT model in the deduction phase and run some tests.
Can you provide me an example code to do that?
On the contrary, how can I adapt the `mixtral_double_deduct()` function for this purpose?

By the way, thanks for the quick reply on the previous issue.

**Comment by Yuchen413** [comment]
Hello, I just added a demo function using GPT for deduction. You can build upon it as you need. Try: python main.py --gpt_deduct_demo

**Comment by angel-ayala** [comment]
Nice!
Thanks for the quick reply, I just need to comment the line 14 in the utils.py file where is [defined the classifier variable](https://github.com/Yuchen413/AnomalyRuler/blob/master/utils.py#L14).

There is any chance to provide and example use of the GPT model as VLM in the induction stage?
As I don't have any GPU right now I would like to test all the stages using the OpenAI models.

**Comment by Yuchen413** [comment]
The induction is by default using the GPT.

**Comment by angel-ayala** [comment]
Oh great, I will test it, thanks!
