### ISSUE TITLE
GPU Usage and Inference Time Optimization for Video Processing

### ISSUE THREAD

**Issue by Changryeol-Jeon** [Yuchen413/AnomalyRuler#5]
I would like to know the amount of GPU consumption when conducting inference on streaming videos or MP4 files using this system, and I would also appreciate recommendations on how to further reduce it. Additionally, what is the typical FPS during inference?

**Comment by Yuchen413** [comment]
It needs at least 40GB to run the visual perception from frames. In our experiments we use the float16 models, you can look at the 4-bit quantization version, which is claimed to use just 11GB GPU. The datasets are already converted to image frames when we have them. It should be 15FPS for ShanghaiTech.
